server:
  port: 8080
server.servlet.contextPath: /finqube
spring.application.name: finqube
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finqube
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
          maximum-pool-size: 10
          minimum-idle: 2
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true	
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
mfu:
  base-url: https://test.mfuonline.com:4091
  entity-id: 40008J
  public-key: DVUMNBV7QVCETMKM
  iv-key: CU0OCPM1ADL2PPZQ
  client-id: MIDFINUAT
  client-secret: MI)D90fI&4
eCAN:
  header:
    userId: MIDFINUAT
    password: MI)D90fI&4
    version: 1.00
  api:
    validECan: "https://test.mfuonline.com:4091/MFUCanFillEezzService"
    validCanBank: "https://test.mfuonline.com:4091/ApiFinTechBankValidationService"
finqube:
  entityId: 40008J
  uniqueId: 123456789012345
  requestType: CANINDREG
  loginUserId: MIDFINECUAT
  version: "1.00"
  encryptedPassword: w73PEHWQKGCNNVsc/NiM5g==
  password: MI)D90fI&4
  entityEmail: naveen.d@digibytetechnologies.com
