server:
  port: 8080
server.servlet.contextPath: /finqube
spring.application.name: finqube
spring.profiles.active: dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finqube
    username: finqube
    password: February@2025
    driver-class-name: org.postgresql.Driver
    hikari:
          maximum-pool-size: 10
          minimum-idle: 2
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true	
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
